// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdyUhpQikPylp8HFYulGIuAfJ4mnh6H3w',
    appId: '1:408142062433:web:ec9c9783b6f38cdb77db20',
    messagingSenderId: '408142062433',
    projectId: 'todo-app-c72b9',
    authDomain: 'todo-app-c72b9.firebaseapp.com',
    storageBucket: 'todo-app-c72b9.appspot.com',
    measurementId: 'G-5RZ7H7DD15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwLWObMkcPergpW7uudHdxaY19h8JRp_I',
    appId: '1:408142062433:android:6ee1bdd8ca2e558277db20',
    messagingSenderId: '408142062433',
    projectId: 'todo-app-c72b9',
    storageBucket: 'todo-app-c72b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKsSYPvlMHL7DF_S7KwxwXol_oHKs4qyo',
    appId: '1:408142062433:ios:d3fcf6442e4d11a477db20',
    messagingSenderId: '408142062433',
    projectId: 'todo-app-c72b9',
    storageBucket: 'todo-app-c72b9.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKsSYPvlMHL7DF_S7KwxwXol_oHKs4qyo',
    appId: '1:408142062433:ios:719b5278ff7168e877db20',
    messagingSenderId: '408142062433',
    projectId: 'todo-app-c72b9',
    storageBucket: 'todo-app-c72b9.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
